language: node_js
node_js:
  - "7.6"

addons:
  coveralls:
    repo_token: YAK9nniKwGQRQhJ0Aru7aAtkraD0WLdQD

after_script:
  - "yarn coverage"
  - "cat ./docs/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
